[package]
name = "uuid-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "1.1.0"

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",
]



[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "uuid_benchmark"
harness = false
